### ISSUE TITLE
obss/sahi reposu ile karsilastirma

### ISSUE THREAD

**Issue by fcakyon** [kadirnar/sahi-lite#2]
Selamlar Kadir,

Bu reporunun `obss/sahi` reposu ile arasindaki farklari yazabilir misin readme'ye? Hangi acilardan daha sade? Ilk gozume carpan: Detectron2 ve MMDetection destegi cikarilmis, baska farklar da var midir?

**Comment by kadirnar** [comment]
Merhaba @fcakyon Hocam,

SAHI kütüphanesine katkı yapmaya ilk başladığımda uzun kod blokları,test yapısı,class yapısı gibi nedenlerden dolayı çekinmiştim. Öğrencilerin SAHI yapısına çok daha rahat alışabilmesi için kodları kısaltmaya çalışıyorum. Onun dışında görselleştirme tarafında eklemek istediğim modüller var.

Bu reponun sürekli güncel kalabilmesi için SAHI reposundan fork etseydim belki daha iyi olurdu. SAHI'yi kullanmak isteyenlere ana repoya yönlendirme yapılacak.

**Comment by kadirnar** [comment]
SAHI kütüphanesini bir web uygulamasını dönüştürmek için, bana sadece predict kodları lazım. Web uygulamalarına entegre etmek için de böyle bir repo oluşturmayı hedefledim.

**Comment by fcakyon** [comment]
@kadirnar anliyorum demek istedigini ama aradaki farklari daha net bir sekilde listeleyebilirsen (readmeye bir tablo seklinde eklenebilir) kullanicilar icin daha kullanisli olur bence 👍

**Comment by kadirnar** [comment]
Repoyu istediğim basit haline getirebilirsem tutorial oluşturmayı hedefliyorum. Dediğiniz gibi ana repo ile ilgili farkları yazarsam hedef kullanıcıya daha rahat ulaşabilirim. Geri dönüşünüz için teşekkür ederim @fcakyon hocam
